# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f639cfdf385c15883ebd0b5f518e01d58d374da729ca2e829d8ce78bbed4edeceb5a8964d5c7ed5f3fbe8ba85dd3b686b2e9a9882e68ab072f9540396ed57ec9

test:
  secret_key_base: 269960caeee9cd7dca54a0a3c6dabf875979cb45c66a47fe55df2719d9729d33ab244531b7604c522c617469ab075474e6e66642d72637de863f3336443ba996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
